### ISSUE TITLE
Event on read file

### ISSUE THREAD

**Issue by camael24** [hoaproject/File#12]
Hi

Its probally not an bug, but when I run this code https://gist.github.com/camael24/5ff0e3718201845498f7

I have : 
```
$ php main.php
58a49b3689d699cb72ffda7252d99fcb
```

Instead of 

```
$ php main.php
ProgressProgressProgressProgressProgressProgressProgressProgress ....
58a49b3689d699cb72ffda7252d99fcb
```

An idea where I was wrong ?

ps: Same here : https://gist.github.com/8f222c0182a379da166c

**Comment by camael24** [comment]
in addition I search to download this file locally, I use Read to download and Write to write in local file, maybe I make a mistake :dancer:

**Comment by Hywan** [comment]
@camael24 You can use `ReadWrite`.

**Comment by Hywan** [comment]
When making a `new`, the stream is opened directly. We can “wait” and call `open` manually. Here is how:
```php
<?php

require '/usr/local/lib/Hoa/Core/Core.php';

use Hoa\Core;
use Hoa\File;

$file = new File\Read(
    'http://hoa-project.net/En',
    File::MODE_READ,
    null,
    true /* wait before opening */
);

$file->on('progress', function ( Core\Event\Bucket $bucket ) {

    $data = $bucket->getData(); /* check all the data */
    var_dump($data['transferred']);

    return;
});

$file->open(); /* now we attached the event, we can open the file */

echo md5($file->readAll());
```
More information about what you receive in the event handler: https://github.com/hoaproject/Stream/blob/33194d3b2239e63f699591dbb388fa62af5bfe97/Stream.php#L550-L591.

**Comment by camael24** [comment]
Thanks a lot :)
